data <- read.table("household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
mydata <- data[which(data$Date == "2007-02-01" | data$Date == "2007-02-02"), ]
mydata$Time <- strptime(paste(as.Date(mydata$Date), mydata$Time), format = "%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfrow = c(2, 2))
with(mydata, plot(Time, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with(mydata, plot(Time, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
plot(mydata$Time, mydata$Sub_metering_1, type = 'l', col = 'black', ylim = c(0, 40), ann = FALSE)
par(new = TRUE)
plot(mydata$Time, mydata$Sub_metering_2, type = 'l', col = 'red'  , ylim = c(0, 40), ann = FALSE)
par(new = TRUE)
plot(mydata$Time, mydata$Sub_metering_3, type = 'l', col = 'blue' , ylim = c(0, 40), ann = FALSE) 
legend("topright", legend = c("sub_metering_1", "sub_metering_2", "sub_metering_3"), col = c("black", "red", "blue"), lty = c(1, 1, 1))
title(ylab = "Energy sub metering")
with(mydata, plot(Time, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_Reactive_Power"))
dev.off()
